### ISSUE TITLE
Verify sample LKM module gets loaded into the Beaglebone

### ISSUE THREAD

**Issue by GuruprashanthKrishnakumar** [cu-ecen-aeld/final-project-jordicrosmompart#2]
**Definition of Done (DOD)**
- Add sample LKM into kernel using Buildroot.
- Verify sample LKM is loaded on boot and functions properly.

**Blockers**
- [Bring up of Buildroot environment](https://github.com/cu-ecen-aeld/final-project-jordicrosmompart/issues/1) - COMPLETED

**Comment by jordicrosmompart** [comment]
Status: new sample module (aesdchar) has been setup and included to the kernel image. TODO: flash it and prove it works.

**Comment by jordicrosmompart** [comment]
Status: CLOSED - Successfully used LKM in the BeagleBone image, with init.d included

**Comment by jordicrosmompart** [comment]
Update: Buildroot version and Kernel version have been changed. While we have successfully loaded an LKM to the BeagleBone, it also will be tested for the currently used versions.

**Comment by GuruprashanthKrishnakumar** [comment]
Status: CLOSED - Successfully used LKM in the BeagleBone image, with init.d included

**Comment by jordicrosmompart** [comment]
Status: CLOSED. Successfully loaded an LKM as well as init.d scripts.
Successfully used the LKM in the BBB.

PS: Above interactions with this issue were tests performed by Guru and I. Do not mind content below "Update" comment and this update.

**Comment by GuruprashanthKrishnakumar** [comment]
Closed: Created a new patch that updated am335x-bone-common.dtsi as per the latest beagleboard linux repo. Updated am33xx-l4.dtsi to enable the UARTs. UARTs are still not enabled. 

Will try to revert to an older version of buildroot to see if the issue gets resolved. 
Otherwise, will try to switch to a device tree overlay approach,

A follow-up [issue](https://github.com/cu-ecen-aeld/final-project-jordicrosmompart/issues/12) has been created to track this.

**Comment by jordicrosmompart** [comment]
Last commit associated with this issue: https://github.com/cu-ecen-aeld/final-project-jordicrosmompart/commit/1dd177d7a4a3904f3b35409dfd92f303d3571d5d

![samplemodule](https://user-images.githubusercontent.com/91290525/201765583-1e056475-c3ae-4d46-8cfc-d1aa097a13d0.JPG)


PS: Above interactions with this issue were tests performed by Guru and I. Do not mind content below "Status: CLOSED" comment and this update.
