### ISSUE TITLE
User-space server socket application implementation

### ISSUE THREAD

**Issue by GuruprashanthKrishnakumar** [cu-ecen-aeld/final-project-jordicrosmompart#6]
**Definition of Done (DOD)**
- Implement/leverage socket code to communicate between the two BeagleBone devices.
- Verify that the socket application functions as expected (server).

**Blockers**
[HM-11 BLE device driver implementation - Integration with UART driver](https://github.com/cu-ecen-aeld/final-project-jordicrosmompart/issues/13) - COMPLETED.

**Comment by jordicrosmompart** [comment]
TASK CLOSED:
Commit: https://github.com/cu-ecen-aeld/final-project-GuruprashanthKrishnakumar/tree/a3d1c9eca60efd9dc541e3d3c0a68b3dc4068b57

- Server is successful between server and client
![image](https://user-images.githubusercontent.com/91290525/205520185-69c3ae2a-a30e-4a3a-a43b-3c833abcbe7a.png)

- The socket server has the following features: main thread interacts with the driver. A server thread waits for new connections and periodically cleans terminated connections. Once a new connection is accepted, a new thread sends new heart rate values to the client. The server accepts multiple clients at the same time, it cares about concurrent access to shared variables between threads, and checks all error codes of functions used (including HM11 ioctl commands).
