### ISSUE TITLE
User-space client socket application implementation

### ISSUE THREAD

**Issue by jordicrosmompart** [cu-ecen-aeld/final-project-jordicrosmompart#7]
**Definition of Done (DOD)**
- Implement/leverage socket code to communicate with the server socket code.
- Verify that the socket application functions as expected (client).
- Verify that client and server beaglebone blacks are able to communicate over socket using LAN.

**Blockers**
[User-space server socket application implementation](https://github.com/cu-ecen-aeld/final-project-jordicrosmompart/issues/6)

**Comment by GuruprashanthKrishnakumar** [comment]
[Code](https://github.com/cu-ecen-aeld/final-project-GuruprashanthKrishnakumar/blob/master/socket_client/socket_client.c)

Verified that the server and client socket applications are able to communicate.
![image](https://user-images.githubusercontent.com/97482748/205522203-1b3c6707-6f21-43f8-a948-1b7cd3741da1.png)

Verified that client and server beaglebone blacks are able to communicate over socket using LAN (please check demo video). 

Associated commit - https://github.com/cu-ecen-aeld/final-project-GuruprashanthKrishnakumar/commit/d0fff2d600150c38a68e83f7bba370627b2bd4ca
